/** @type {import('./alienDuck').Card[]} */
export const cardCollection = [
  {
    id: "c001",
    name: "Hero",
    power: 12,
    maxPower: 12,
    actionSlot: 2,
    storeSlot: 1,
    type: "HERO",
    work: "PROTECT",
    side: "LIGHT",
    src: "alien_invader.png",
    rule: "Deals damage equal to power to the hero."
  },
  {
    id: "c002",
    name: "Cosmic Defender",
    power: 10,
    maxPower: 10,
    actionSlot: 1,
    storeSlot: 0,
    type: "SPACE-SHIP",
    work: "HIT",
    side: "DARK",
    src: "cosmic_defender.png",
    rule: "Blocks an attack from an ALIEN."
  },
  {
    id: "c003",
    name: "Asteroid Field",
    power: 6,
    maxPower: 6,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "asteroid_field.png",
    rule: "Aliens passing through lose 1 power."
  },
  {
    id: "c004",
    name: "Laser Blaster",
    power: 3,
    maxPower: 3,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "HIT",
    side: "LIGHT",
    src: "laser_blaster.png",
    rule: "Use to deal 2 damage to an ALIEN."
  },
  {
    id: "c005",
    name: "Alien Overlord",
    power: 10,
    maxPower: 10,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_overlord.png",
    rule: "Deals heavy damage to the hero."
  },
  {
    id: "c006",
    name: "Space Pirate",
    power: 9,
    maxPower: 9,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "space_pirate.png",
    rule: "Steals one GADGET from the hero."
  },
  {
    id: "c007",
    name: "Healing Pod",
    power: 7,
    maxPower: 7,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "RAISE",
    side: "LIGHT",
    src: "healing_pod.png",
    rule: "Restores 3 power to the hero."
  },
  {
    id: "c008",
    name: "Galactic Map",
    power: 5,
    maxPower: 5,
    actionSlot: 0,
    storeSlot: 1,
    type: "GADGET",
    work: "PROTECT",
    side: "LIGHT",
    src: "galactic_map.png",
    rule: "Reveals the next 3 cards in the deck."
  },
  {
    id: "c009",
    name: "Alien Symbiote",
    power: 9,
    maxPower: 9,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_symbiote.png",
    rule: "Reduces hero's power by 1 each turn."
  },
  {
    id: "c010",
    name: "Space Station",
    power: 7,
    maxPower: 7,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "PROTECT",
    side: "LIGHT",
    src: "space_station.png",
    rule: "Hero can rest here to restore power."
  },
  {
    id: "c011",
    name: "Energy Shield",
    power: 6,
    maxPower: 6,
    actionSlot: 0,
    storeSlot: 1,
    type: "GADGET",
    work: "PROTECT",
    side: "LIGHT",
    src: "energy_shield.png",
    rule: "Blocks the next attack completely."
  },
  {
    id: "c012",
    name: "Alien Hatchling",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_hatchling.png",
    rule: "Weak but can grow stronger."
  },
  {
    id: "c013",
    name: "Black Hole",
    power: 10,
    maxPower: 10,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "black_hole.png",
    rule: "Destroys all cards in play."
  },
  {
    id: "c014",
    name: "Quantum Drive",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "WORTH",
    side: "LIGHT",
    src: "quantum_drive.png",
    rule: "Skip the next ALIEN card."
  },
  {
    id: "c015",
    name: "Alien Queen",
    power: 8,
    maxPower: 8,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_queen.png",
    rule: "Spawns Alien Hatchlings."
  },
  {
    id: "c016",
    name: "Space Merchant",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: 'ALIEN',
    work: "PROTECT",
    side: "LIGHT",
    src: "space_merchant.png",
    rule: "Trade GADGETS for power."
  },
  {
    id: "c017",
    name: "Meteor Shower",
    power: 8,
    maxPower: 8,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "meteor_shower.png",
    rule: "All players lose 2 power."
  },
  {
    id: "c018",
    name: "Robotic Ally",
    power: 3,
    maxPower: 3,
    actionSlot: 1,
    storeSlot: 0,
    type: "SPACE-SHIP",
    work: "RAISE",
    side: "LIGHT",
    src: "robotic_ally.png",
    rule: "Adds 3 power to hero for one turn."
  },
  {
    id: "c019",
    name: "Space Mine",
    power: 7,
    maxPower: 7,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "WORTH",
    side: "LIGHT",
    src: "space_mine.png",
    rule: "Deals 3 damage to next ALIEN."
  },
  {
    id: "c020",
    name: "Alien Scout",
    power: 5,
    maxPower: 5,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_scout.png",
    rule: "Reveals one of your GADGETS."
  },
  {
    id: "c021",
    name: "Nebula Cloud",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "PROTECT",
    side: "LIGHT",
    src: "nebula_cloud.png",
    rule: "All players have reduced visibility."
  },
  {
    id: "c022",
    name: "Time Warp",
    power: 0,
    maxPower: 0,
    actionSlot: 0,
    storeSlot: 0,
    type: "STORY",
    work: "SKILL",
    side: "LIGHT",
    src: "time_warp.png",
    rule: "Repeat the last action."
  },
  {
    id: "c023",
    name: "Plasma Cannon",
    power: 5,
    maxPower: 5,
    actionSlot: 1,
    storeSlot: 0,
    type: "GADGET",
    work: "HIT",
    side: "LIGHT",
    src: "plasma_cannon.png",
    rule: "Deal 5 damage to an ALIEN."
  },
  {
    id: "c024",
    name: "Alien Warrior",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_warrior.png",
    rule: "Strong attacker."
  },
  {
    id: "c025",
    name: "Wormhole",
    power: 5,
    maxPower: 5,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "wormhole.png",
    rule: "Swap positions with another card."
  },
  {
    id: "c026",
    name: "Alien Artifact",
    power: 10,
    maxPower: 10,
    actionSlot: 0,
    storeSlot: 1,
    type: "GADGET",
    work: "WORTH",
    side: "LIGHT",
    src: "alien_artifact.png",
    rule: "Gain a random effect."
  },
  {
    id: "c027",
    name: "Solar Flare",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "solar_flare.png",
    rule: "All players lose action slots for one turn."
  },
  {
    id: "c028",
    name: "Space Ranger",
    power: 5,
    maxPower: 5,
    actionSlot: 1,
    storeSlot: 0,
    type: "SPACE-SHIP",
    work: "RAISE",
    side: "LIGHT",
    src: "space_ranger.png",
    rule: "Defeats any ALIEN with power less than 5."
  },
  {
    id: "c029",
    name: "Alien Spy",
    power: 3,
    maxPower: 3,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_spy.png",
    rule: "Reveals hero's hand."
  },
  {
    id: "c030",
    name: "Ion Storm",
    power: 3,
    maxPower: 3,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "HIT",
    side: "DARK",
    src: "ion_storm.png",
    rule: "All GADGETS are disabled for one turn."
  },
  {
    id: "c031",
    name: "Holographic Decoy",
    power: 3,
    maxPower: 3,
    actionSlot: 0,
    storeSlot: 1,
    type: "GADGET",
    work: "PROTECT",
    side: "LIGHT",
    src: "holographic_decoy.png",
    rule: "Next attack targets the decoy."
  },
  {
    id: "c032",
    name: "Alien Slime",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "WORTH",
    side: "LIGHT",
    src: "alien_slime.png",
    rule: "Reduces hero's action slots by 1."
  },
  {
    id: "c033",
    name: "Dr. Anomaly",
    power: 9,
    maxPower: 9,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "RAISE",
    side: "LIGHT",
    src: "space_anomaly.png",
    rule: "Random event occurs."
  },
  {
    id: "c034",
    name: "Don Grox",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "LIGHT",
    src: "gravity_well.png",
    rule: "All cards move one spot backward."
  },
  {
    id: "c035",
    name: "Alien Berserker",
    power: 6,
    maxPower: 6,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_berserker.png",
    rule: "Attacks twice per turn."
  },
  {
    id: "c036",
    name: "Space Explorer",
    power: 6,
    maxPower: 6,
    actionSlot: 1,
    storeSlot: 0,
    type: "SPACE-SHIP",
    work: "HIT",
    side: "LIGHT",
    src: "space_explorer.png",
    rule: "Allows drawing an extra card."
  },
  {
    id: "c037",
    name: "Urgent Surgery",
    power: 0,
    maxPower: 0,
    actionSlot: 0,
    storeSlot: 0,
    type: "STORY",
    work: "SKILL",
    side: "LIGHT",
    src: "alien_virus.png",
    rule: "Hero loses 1 power per turn."
  },
  {
    id: "c038",
    name: "Comet",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: "STORY",
    work: "HIT",
    side: "LIGHT",
    src: "comet.png",
    rule: "Deals 3 damage to all."
  },
  {
    id: "c039",
    name: "Alien Psychic",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "HIT",
    side: "DARK",
    src: "alien_psychic.png",
    rule: "Controls hero's next move."
  },
  {
    id: "c040",
    name: "Interstellar Map",
    power: 0,
    maxPower: 0,
    actionSlot: 0,
    storeSlot: 1,
    type: "GADGET",
    work: "SKILL",
    side: "LIGHT",
    src: "interstellar_map.png",
    rule: "Allows choosing the next card."
  },
  {
    id: "c041",
    name: "Supernova",
    power: 7,
    maxPower: 7,
    actionSlot: 0,
    storeSlot: 0,
    type: "STORY",
    work: "HIT",
    side: "LIGHT",
    src: "supernova.png",
    rule: "All cards in play are destroyed."
  },
  {
    id: "c042",
    name: "Alien Ambassador",
    power: 4,
    maxPower: 4,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "RAISE",
    side: "LIGHT",
    src: "alien_ambassador.png",
    rule: "Negotiates peace, restores 5 power to hero."
  },
  {
    id: "c043",
    name: "Bonan Hedwinder",
    power: 8,
    maxPower: 8,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "RAISE",
    side: "LIGHT",
    src: "",
    rule: ""
  },
  {
    id: "c044",
    name: "Dr. Frwhuwhincs",
    power: 6,
    maxPower: 6,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "RAISE",
    side: "LIGHT",
    src: "",
    rule: ""
  },
  {
    id: "c045",
    name: "Yengon",
    power: 10,
    maxPower: 10,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "RAISE",
    side: "LIGHT",
    src: "",
    rule: ""
  },
  {
    id: "c046",
    name: "Infection",
    power: 2,
    maxPower: 2,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "RAISE",
    side: "LIGHT",
    src: "",
    rule: ""
  },
  {
    id: "c047",
    name: "Brew Generator",
    power: 3,
    maxPower: 3,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "WORTH",
    side: "NEUTRAL",
    src: "",
    rule: ""
  },
  {
    id: "c048",
    name: "Plasma Converter",
    power: 5,
    maxPower: 5,
    actionSlot: 0,
    storeSlot: 0,
    type: "GADGET",
    work: "WORTH",
    side: "NEUTRAL",
    src: "",
    rule: ""
  },
  {
    id: "c048",
    name: "Proton Palace",
    power: 6,
    maxPower: 6,
    actionSlot: 0,
    storeSlot: 0,
    type: "LOCATION",
    work: "WORTH",
    side: "NEUTRAL",
    src: "",
    rule: ""
  },
  {
    id: "c049",
    name: "Xeno Princess",
    power: 9,
    maxPower: 9,
    actionSlot: 0,
    storeSlot: 0,
    type: "ALIEN",
    work: "WORTH",
    side: "NEUTRAL",
    src: "",
    rule: ""
  },
  {
    id: "c050",
    name: "Holy Sparrow",
    power: 10,
    maxPower: 10,
    actionSlot: 1,
    storeSlot: 0,
    type: "SPACE-SHIP",
    work: "WORTH",
    side: "LIGHT",
    src: "",
    rule: ""
  },
];
